name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: runsWithNoErrors
      id: runswithnoerrors
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: runsWithNoErrors
        setup-command: ''
        command: gradle test --tests FirstProgram.FirstProgramTester
        timeout: 1
        max-score: 4
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        RUNSWITHNOERRORS_RESULTS: "${{steps.runswithnoerrors.outputs.result}}"
      with:
        runners: runswithnoerrors
